# Generated by Django 5.0.4 on 2024-05-12 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0002_alter_server_server_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
